In [1]:
import numpy as np
import torch

# Using Numpy

In [2]:
#Create a vector
nv = np.array([[1,2,3,4]])
print(nv), print(" ")

#Transpose the Vector Nv
print(nv.T), print(" ")

#Transpose the transpose
nvT= nv.T # Transpose Function
print(nvT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [3]:
# Repeat for matrix
nM = np.array([[1,2,3,4],[5,6,7,8]])
print(nM), print(" ")

#Transpose the Matrix
print(nM.T), print(" ")

#Transpose the Matrix Transpose
nMT = nM.T # Transpose Fuction
print(nMT.T)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]


# Using PyTorch

In [6]:
# Create a vector
tv = torch.tensor([1,2,3,4])
print(tv), print(" ")

#Transpose it
print(tv.T), print(" ")

# Transpose the Transpose
tvT = tv.T
print(tvT.T)

tensor([1, 2, 3, 4])
 
tensor([1, 2, 3, 4])
 
tensor([1, 2, 3, 4])


In [8]:
# Matrix using Pytorch
# Repeat for matrix
tM = torch.tensor([[1,2,3,4],[5,6,7,8]])
print(tM), print(" ")

#Transpose the Matrix
print(tM.T), print(" ")

#Transpose the Matrix Transpose
tMT = tM.T # Transpose Fuction
print(tMT.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [10]:
# Examine data type
print(f"Variable nv is of type: {type(nv)}")
print(f"Variable nM is of type: {type(nM)}")
print(f"Variable tv is of type: {type(tv)}")
print(f"Variable tM is of type: {type(tM)}")


Variable nv is of type: <class 'numpy.ndarray'>
Variable nM is of type: <class 'numpy.ndarray'>
Variable tv is of type: <class 'torch.Tensor'>
Variable tM is of type: <class 'torch.Tensor'>
