In [4]:
import numpy as np
import torch

#  Using Numpy

In [6]:
# create some radom matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# Try some multiply
print(np.round(A@B, 2)), print(" ") # @ is a symbol for Matrix Multiply
print(np.round(C.T@A, 2)), print(" ") # @ is a symbol for Matrix Multiply

[[ 3.79 -0.97 -1.3   1.7  -7.54]
 [ 3.91  0.68  2.63  1.08 -1.3 ]
 [-5.54 -0.51 -3.86  2.59 -2.35]]
 
[[-1.52  0.06  1.49  1.68]
 [-0.17 -0.14  1.98 -0.48]
 [ 0.7   0.67 -2.65 -1.89]
 [-2.86  1.08 -0.14  1.82]
 [-2.34  1.35  2.69 -1.92]
 [-1.96  2.3  -1.37 -3.25]
 [ 0.85 -0.92  0.73  1.07]]
 


(None, None)

# Using PyTorch

In [11]:
# create some radom matrices
A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor(C1, dtype=torch.float)

# Try some multiply
print(np.round(A@B, 2)), print(" ") # @ is a symbol for Matrix Multiply
print(np.round(A@C1, 2)), print(" ") # @ is a symbol for Matrix Multiply

tensor([[-1.2800,  0.9000,  1.0800,  0.2900,  0.6000],
        [-2.4100, -2.8800,  1.8500,  0.1300,  2.3100],
        [ 6.5300, -2.4900, -5.3200, -0.0200, -6.8700]])
 
tensor([[-0.3000,  0.3400, -2.8600, -1.3100,  0.1400,  2.6700,  2.7100],
        [ 0.1400,  1.6200, -1.6300,  1.5000,  1.4900, -0.3100, -1.8400],
        [ 0.8900, -3.2400,  4.1400, -1.4000,  2.5500, -3.0500, -2.8000]],
       dtype=torch.float64)
 


(None, None)